platform:ios, '6.0'
pod 'AFNetworking'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
#pod 'FMDB'
#pod 'NSXtensions'
#pod 'TapkuLibrary'
#pod 'MLPAutoCompleteTextField', '~> 1.0'
#pod 'ReactiveCocoa'
